In [1]:
import torch

In [2]:
binary_data = "../src/arginator_protein_classifier/.data/processed_data_binary.pt"
multiclass_data = "../src/arginator_protein_classifier/.data/processed_data_multiclass.pt"

In [3]:
print(type(binary_data))
print(type(multiclass_data))

<class 'str'>
<class 'str'>


In [4]:
binary_data = torch.load(binary_data)
multiclass_data = torch.load(multiclass_data)

In [5]:
print(type(binary_data))
print(type(multiclass_data))

<class 'list'>
<class 'list'>


In [6]:
binary_data

[(tensor([ 0.0074, -0.0068,  0.0168,  ..., -0.0066,  0.0147,  0.0051]), 1),
 (tensor([0.0382, 0.0041, 0.0005,  ..., 0.0168, 0.0647, 0.0180]), 1),
 (tensor([ 0.0326,  0.0139,  0.0101,  ..., -0.0185,  0.0223,  0.0378]), 1),
 (tensor([ 0.0200, -0.0170,  0.0214,  ..., -0.0027,  0.0143,  0.0055]), 1),
 (tensor([ 0.0372,  0.0065, -0.0062,  ..., -0.0320,  0.0263,  0.0268]), 1),
 (tensor([ 0.0507,  0.0190, -0.0058,  ..., -0.0036, -0.0049,  0.0356]), 1),
 (tensor([ 0.0257,  0.0052, -0.0150,  ...,  0.0085,  0.0610,  0.0395]), 1),
 (tensor([ 0.0426,  0.0048, -0.0005,  ..., -0.0058,  0.0235,  0.0386]), 1),
 (tensor([ 0.0465,  0.0916,  0.0345,  ..., -0.0187, -0.0447,  0.0008]), 1),
 (tensor([ 0.0500,  0.0956,  0.0356,  ..., -0.0163, -0.0480,  0.0029]), 1),
 (tensor([ 0.0126,  0.0111,  0.0182,  ...,  0.0055,  0.0023, -0.0082]), 1),
 (tensor([ 0.0443,  0.0991,  0.0293,  ...,  0.0034, -0.0275,  0.0012]), 1),
 (tensor([ 0.0438,  0.0063,  0.0007,  ..., -0.0195,  0.0301,  0.0494]), 1),
 (tensor([ 0.0345,

In [7]:
binary_embeddings, binary_labels = zip(*binary_data)
multi_embeddings, multi_labels = zip(*multiclass_data)
print(type(binary_labels), type(multi_labels))


<class 'tuple'> <class 'tuple'>


In [8]:
binary_labels_tensor = torch.tensor(binary_labels)
multi_labels_tensor = torch.tensor(multi_labels)
print(type(binary_labels_tensor))

<class 'torch.Tensor'>


In [9]:
b_labels, freqs = torch.unique(binary_labels_tensor, return_counts=True)
m_labels, m_freqs = torch.unique(multi_labels_tensor, return_counts=True)


In [10]:
for val, count in zip(m_labels, m_freqs):
    print(f"  Class {val.item()}: {count.item()} samples")

  Class 0: 1501 samples
  Class 1: 513 samples
  Class 2: 1530 samples
  Class 3: 1278 samples
  Class 4: 60000 samples


In [11]:
for val, count in zip(b_labels, freqs):
    print(f"  Class {val.item()}: {count.item()} samples")

  Class 0: 60000 samples
  Class 1: 4822 samples
